# Generated by Django 5.0.1 on 2024-02-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "post",
            "0003_remove_like_value_alter_like_id_alter_like_owner_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
